title: STRATOS Publications Datasets
description: Information and download links to datasets used in STRATOS publications
# Site navigation
navbar_links:
  - title: "About"
    url: "/about/"   # Matches the permalink in about.md
  - title: "Content"
    url: "/content/" # Matches the permalink in content.md
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
