theme: minima
title: STRATOS Datasets
header_image: <img src="/Image/stratos_logo.png"/ style="height: 50px;">
description: Information and download links to datasets used in STRATOS publications
# Site navigation
navbar_links:
  - title: "Data sets"
    url: "/content/" # Matches the permalink in content.md
  - title: "About"
    url: "/about/"   # Matches the permalink in about.md

