theme: jekyll-theme-slate
title: STRATOS Publications Datasets
navbar_links:
  - title: "Home"
    url: "/"
exclude:
  - README.md                       # Exclude from processing
include:
  - content.md
