theme: jekyll-theme-slate
title: STRATOS Publications Datasets
# Site navigation
navbar_links:
  - title: "About"
    url: "/about/"   # Matches the permalink in about.md
  - title: "Content"
    url: "/content/" # Matches the permalink in content.md
